---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: GoLang Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3

      - name: Setup GoLang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Golang CI lint
        uses: golangci/golangci-lint-action@v3

      - name: Run StaticCheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3

      - name: Setup GoLang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run unit tests
        run: make unit-tests
